- name: List all enabled services
  hosts: all
  become: true
  tasks:
    - name: Get list of enabled services
      command: systemctl list-unit-files --type=service --state=enabled
      register: services

    - name: Show enabled services
      debug:
        var: services.stdout_lines
