---
- name: Actualizare index.html și restart Nginx dacă este modificat
  hosts: all
  become: yes

  tasks:
    - name: Copiere fișier index.html existent către /usr/share/nginx/html
      copy:
        src: ../index.html  
        dest: /usr/share/nginx/html/index.html
        owner: root
        group: root
        mode: '0644'
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
